-- DROP SCHEMA dbo;

CREATE SCHEMA dbo;
-- ONCOVO.dbo.FOTO definition

-- Drop table

-- DROP TABLE ONCOVO.dbo.FOTO;

CREATE TABLE ONCOVO.dbo.FOTO (
	ID_FOTO int IDENTITY(0,1) NOT NULL,
	NOME_IMAGEM nvarchar(100) COLLATE Latin1_General_CI_AS NOT NULL,
	IMAGEM image NOT NULL,
	DATA_ATIVACAO date NOT NULL,
	DATA_ATUALIZACAO date NOT NULL,
	DATA_DESATIVACAO date NOT NULL,
	CONSTRAINT FOTO_PK PRIMARY KEY (ID_FOTO)
);


-- ONCOVO.dbo.OPCAO_PAGAMENTO definition

-- Drop table

-- DROP TABLE ONCOVO.dbo.OPCAO_PAGAMENTO;

CREATE TABLE ONCOVO.dbo.OPCAO_PAGAMENTO (
	ID_PAGAMENTO int IDENTITY(0,1) NOT NULL,
	TIPO_PAGAMENTO nvarchar(100) COLLATE Latin1_General_CI_AS NOT NULL,
	BANDEIRA nvarchar(100) COLLATE Latin1_General_CI_AS NULL,
	DATA_ATIVACAO date NOT NULL,
	DATA_ATUALIZACAO date NOT NULL,
	DATA_DESATIVACAO date NOT NULL,
	CONSTRAINT OPCAO_PAGAMENTO_PK PRIMARY KEY (ID_PAGAMENTO)
);


-- ONCOVO.dbo.PESSOA definition

-- Drop table

-- DROP TABLE ONCOVO.dbo.PESSOA;

CREATE TABLE ONCOVO.dbo.PESSOA (
	ID_PESSOA int IDENTITY(0,1) NOT NULL,
	NOME nvarchar(60) COLLATE Latin1_General_CI_AS NOT NULL,
	TELEFONE nvarchar(14) COLLATE Latin1_General_CI_AS NOT NULL,
	EMAIL nvarchar(100) COLLATE Latin1_General_CI_AS NOT NULL,
	[LOGIN] nvarchar(20) COLLATE Latin1_General_CI_AS NOT NULL,
	SENHA nvarchar(20) COLLATE Latin1_General_CI_AS NOT NULL,
	CODIGO_NACIONAL nvarchar(100) COLLATE Latin1_General_CI_AS NOT NULL,
	SEXO nvarchar(20) COLLATE Latin1_General_CI_AS NULL,
	ENDERECO nvarchar(100) COLLATE Latin1_General_CI_AS NOT NULL,
	DATA_ATIVACAO date NOT NULL,
	DATA_ATUALIZACAO date NOT NULL,
	DATA_DESATIVACAO date NOT NULL,
	CONSTRAINT PESSOA_PK PRIMARY KEY (ID_PESSOA)
);


-- ONCOVO.dbo.PROMOCAO definition

-- Drop table

-- DROP TABLE ONCOVO.dbo.PROMOCAO;

CREATE TABLE ONCOVO.dbo.PROMOCAO (
	ID_PROMOCAO int IDENTITY(0,1) NOT NULL,
	VALOR varchar(100) COLLATE Latin1_General_CI_AS NULL,
	ID_LOCAL int NOT NULL,
	IND_SITUACAO varchar(1) COLLATE Latin1_General_CI_AS NOT NULL,
	DATA_ATIVACAO date NOT NULL,
	DATA_ATUALIZACAO date NOT NULL,
	DATA_DESATIVACAO date NOT NULL,
	CONSTRAINT PROMOCAO_PK PRIMARY KEY (ID_PROMOCAO)
);


-- ONCOVO.dbo.HOSPEDEIRO definition

-- Drop table

-- DROP TABLE ONCOVO.dbo.HOSPEDEIRO;

CREATE TABLE ONCOVO.dbo.HOSPEDEIRO (
	ID_HOSPEDEIRO int IDENTITY(0,1) NOT NULL,
	ID_PAGAMENTO int NOT NULL,
	NOME_HOSPEDEIRO nvarchar(100) COLLATE Latin1_General_CI_AS NOT NULL,
	ENDERECO_HOSPEDEIRO nvarchar(400) COLLATE Latin1_General_CI_AS NOT NULL,
	DATA_ATIVACAO date NOT NULL,
	DATA_ATUALIZACAO date NOT NULL,
	DATA_DESATIVACAO date NOT NULL,
	CONSTRAINT HOSPEDEIRO_PK PRIMARY KEY (ID_HOSPEDEIRO),
	CONSTRAINT HOSPEDEIRO_FK_1 FOREIGN KEY (ID_PAGAMENTO) REFERENCES ONCOVO.dbo.OPCAO_PAGAMENTO(ID_PAGAMENTO)
);


-- ONCOVO.dbo.[LOCAL] definition

-- Drop table

-- DROP TABLE ONCOVO.dbo.[LOCAL];

CREATE TABLE ONCOVO.dbo.[LOCAL] (
	ID_LOCAL int IDENTITY(0,1) NOT NULL,
	ID_HOSPEDEIRO int NOT NULL,
	ID_PROMOCAO int NOT NULL,
	ID_FOTO int NOT NULL,
	NOME_LOCAL nvarchar(60) COLLATE Latin1_General_CI_AS NOT NULL,
	DSC_LOCAL nvarchar(4000) COLLATE Latin1_General_CI_AS NULL,
	DATA_ATIVACAO date NOT NULL,
	DATA_ATUALIZACAO date NOT NULL,
	DATA_DESATIVACAO date NOT NULL,
	CONSTRAINT LOCAL_PK PRIMARY KEY (ID_LOCAL),
	CONSTRAINT LOCAL_FK_1 FOREIGN KEY (ID_FOTO) REFERENCES ONCOVO.dbo.FOTO(ID_FOTO),
	CONSTRAINT LOCAL_FK_2 FOREIGN KEY (ID_HOSPEDEIRO) REFERENCES ONCOVO.dbo.HOSPEDEIRO(ID_HOSPEDEIRO),
	CONSTRAINT LOCAL_FK_3 FOREIGN KEY (ID_PROMOCAO) REFERENCES ONCOVO.dbo.PROMOCAO(ID_PROMOCAO)
);


-- ONCOVO.dbo.HOSPEDAGEM definition

-- Drop table

-- DROP TABLE ONCOVO.dbo.HOSPEDAGEM;

CREATE TABLE ONCOVO.dbo.HOSPEDAGEM (
	ID_HOSPEDAGEM int IDENTITY(0,1) NOT NULL,
	DATA_CHECKIN date NOT NULL,
	DATA_CHECKOUT date NOT NULL,
	NUMERO_HOSPEDES int NOT NULL,
	ID_PESSOA int NOT NULL,
	ID_LOCAL int NOT NULL,
	CONSTRAINT HOSPEDAGEM_PK PRIMARY KEY (ID_HOSPEDAGEM),
	CONSTRAINT HOSPEDAGEM_FK FOREIGN KEY (ID_PESSOA) REFERENCES ONCOVO.dbo.PESSOA(ID_PESSOA),
	CONSTRAINT HOSPEDAGEM_FK_1 FOREIGN KEY (ID_LOCAL) REFERENCES ONCOVO.dbo.[LOCAL](ID_LOCAL)
);
